#!/bin/bash

# which lncli
LNCLI=/usr/local/bin/lncli

# Archive
ARCHIVE=/mnt/storage/snapshots

pretty_time () {
  date -d @$1 +"%Y-%m-%d_%H:%M:%S"
}

# Time
TIMESTAMP=$(date +'%s')
PRETTY_TIME=$(pretty_time $TIMESTAMP)
COUNT=$(ls $ARCHIVE/*.json | wc -l)
echo $COUNT
$LNCLI describegraph | jq -c . > $ARCHIVE/$PRETTY_TIME.json

if [ "$COUNT" -gt 9 ] 
then
	tar -czvf $ARCHIVE/archive/$TIMESTAMP.tar.gz $ARCHIVE/*.json 
	rm $ARCHIVE/*.json
fi
